modLoader = "javafml"
loaderVersion = "[4,)"
license = "MIT"

[[mods]]
modId = "openallay_hello_extension"
version = "0.1.0"
displayName = "OpenAllay Hello Extension"
description = "Minimal external OpenAllay Extension example."

[[dependencies.openallay_hello_extension]]
modId = "neoforge"
type = "required"
versionRange = "[26.2.0.25-beta,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.openallay_hello_extension]]
modId = "minecraft"
type = "required"
versionRange = "[26.2,26.3)"
ordering = "NONE"
side = "BOTH"

[[dependencies.openallay_hello_extension]]
modId = "openallay"
type = "required"
versionRange = "[0.2.0,0.3.0)"
ordering = "AFTER"
side = "BOTH"
